name: recommendation_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  geolocator: ^10.1.0
  health: ^10.2.0
  sensors_plus: ^4.0.2
  http: ^1.1.0
  flutter_activity_recognition: ^4.0.0
  shared_preferences: ^2.2.2  # 新增依赖

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - source/scene.json
